/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import io.Archive;
import modele.*;
import org.json.simple.parser.ParseException;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.HashMap;

/**
 * @author Admin
 */
public class FenSaisie extends javax.swing.JFrame {

    /**
     * Creates new form FenResumeNew
     */

    private ListeRepresentants listeRepresentants = new ListeRepresentants();
    private HashMap<String, CategorieEmploye> categories = new HashMap<>();

    private RegistreFrais registreFrais = new RegistreFrais();

    public FenSaisie() {
        initComponents();
    }

    public FenSaisie(ListeRepresentants listeRepresentants, HashMap<String, CategorieEmploye> categories) {
        this();
        this.listeRepresentants = listeRepresentants;
        this.categories = categories;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        btnG = new javax.swing.ButtonGroup();
        rbtnTra = new javax.swing.JRadioButton();
        rbtnHeb = new javax.swing.JRadioButton();
        rbtnRepas = new javax.swing.JRadioButton();
        buttonGroup14 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblRep = new javax.swing.JLabel();
        txtRep = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rbtnRepas2 = new javax.swing.JRadioButton();
        rbtnHeber2 = new javax.swing.JRadioButton();
        rbtnTrans2 = new javax.swing.JRadioButton();
        javax.swing.JPanel jPan2 = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        lblMont = new javax.swing.JLabel();
        txtMont = new javax.swing.JTextField();
        lblType = new javax.swing.JLabel();
        trans = new javax.swing.JComboBox<>();
        txtDate = new javax.swing.JFormattedTextField();
        lblLimite = new javax.swing.JLabel();
        btnQui = new javax.swing.JButton();
        btnSup = new javax.swing.JButton();
        btnAjou = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAffichage = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnEnregistre = new javax.swing.JButton();

        rbtnTra.setText("Transport");
        rbtnTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTraActionPerformed(evt);
            }
        });

        rbtnHeb.setText("Hébergement");
        rbtnHeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnHebActionPerformed(evt);
            }
        });

        rbtnRepas.setText("Repas");
        rbtnRepas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRepasActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblRep.setText("Numéro de représentant");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Catégorie", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        rbtnRepas2.setText("Repas");

        rbtnHeber2.setText("Hébergement");

        rbtnTrans2.setText("Transport");
        rbtnTrans2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTrans2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(rbtnRepas2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbtnHeber2)
                .addGap(18, 18, 18)
                .addComponent(rbtnTrans2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnRepas2)
                    .addComponent(rbtnHeber2)
                    .addComponent(rbtnTrans2))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblRep)
                .addGap(42, 42, 42)
                .addComponent(txtRep, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRep)
                    .addComponent(txtRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPan2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDate.setText("Date (yyyy-mm-dd):");

        lblMont.setText("Montant:");

        lblType.setLabelFor(trans);
        lblType.setText("Type de transport");

        trans.setEditable(true);
        trans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auto", "Train", "Avion" }));
        trans.setEnabled(false);

        try {
            txtDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDate.setText("    -    -  ");
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPan2Layout = new javax.swing.GroupLayout(jPan2);
        jPan2.setLayout(jPan2Layout);
        jPan2Layout.setHorizontalGroup(
            jPan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPan2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblMont)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMont, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblType)
                .addGap(18, 18, 18)
                .addComponent(trans, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPan2Layout.setVerticalGroup(
            jPan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPan2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(lblMont)
                    .addComponent(txtMont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblType)
                    .addComponent(trans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        lblLimite.setText("Note: (ex: max $25 / jour)");

        btnQui.setText("Quitter");
        btnQui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuiActionPerformed(evt);
            }
        });

        btnSup.setText("Supprimer");
        btnSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupActionPerformed(evt);
            }
        });

        btnAjou.setText("Ajouter");
        btnAjou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouActionPerformed(evt);
            }
        });

        tblAffichage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Prénom", "Catégorie", "Date", "Type de frais", "Montant", "Remboursement"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAffichage.setEnabled(false);
        tblAffichage.setFocusable(false);
        tblAffichage.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(tblAffichage);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("ENREGISTREMENT DES FRAIS REMBOURSABLES");

        btnEnregistre.setText("Enregistrer");
        btnEnregistre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(btnQui, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(btnSup, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAjou, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnregistre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblLimite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSup)
                    .addComponent(btnAjou)
                    .addComponent(btnQui)
                    .addComponent(btnEnregistre))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPan2.getAccessibleContext().setAccessibleName("");
        jPan2.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
     
    private void btnSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupActionPerformed
        registreFrais.supprimerDerniereDepenseEnregistree();
        registreFrais.listerFraisPourUI(tblAffichage);
    }//GEN-LAST:event_btnSupActionPerformed

    private void btnAjouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouActionPerformed
        try {
            listeRepresentants = Archive.lecture("c:/temp/representants.json", categories);
        } catch (FileNotFoundException e1) {
            JOptionPane.showMessageDialog(null, "Problème de fichier en entrée", "Erreur de fichier", JOptionPane.ERROR_MESSAGE);
        } catch (IOException e2) {
            JOptionPane.showMessageDialog(null, "Problème de fichier en sortie", "Erreur de fichier", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException e3) {
            JOptionPane.showMessageDialog(null, "Problème de conversion de fichier", "Erreur de fichier", JOptionPane.ERROR_MESSAGE);
        }

        Employe employe = listeRepresentants.rechercherEmployeParId(txtRep.getText());
        double montantFrais = Double.parseDouble(txtMont.getText());
        Frais frais = new FraisRepas();

        if(rbtnHeber2.isSelected())
            frais = new FraisHebergement();
        else if(rbtnTrans2.isSelected())
            frais = new FraisDeplacement();

        double montantRemboursement = frais.calculerRemboursementFrais(employe, montantFrais);

        if(rbtnRepas2.isSelected())
            registreFrais.ajouterFrais(new FraisRepas(employe, "Repas", montantFrais, txtDate.getText(), montantRemboursement));
        else if(rbtnHeber2.isSelected())
            registreFrais.ajouterFrais(new FraisHebergement(employe, "Hébergement", montantFrais, txtDate.getText(), montantRemboursement));
        //else if(rbtnTrans2.isSelected())
            //registreFrais.ajouterFrais(new FraisDeplacement(employe, "Déplacement", montantFrais, txtDate.getText(), montantRemboursement));

        registreFrais.listerFraisPourUI(tblAffichage);

    }//GEN-LAST:event_btnAjouActionPerformed

    public void reset() {
        txtRep.setText(null);
        txtDate.setText(null);
        txtMont.setText(null);
        DefaultTableModel model = (DefaultTableModel) tblAffichage.getModel();
        model.setRowCount(0);
        registreFrais = new RegistreFrais();
    }

    private void combTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combTypeActionPerformed

    private void btnQuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuiActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuiActionPerformed


    private void rbtnRepasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRepasActionPerformed

btnG.add(rbtnRepas);
btnG.add(rbtnHeb);
btnG.add(rbtnTra);


    }//GEN-LAST:event_rbtnRepasActionPerformed

    private void rbtnHebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnHebActionPerformed

    }//GEN-LAST:event_rbtnHebActionPerformed

    private void rbtnTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTraActionPerformed
  
    }//GEN-LAST:event_rbtnTraActionPerformed

    private void btnEnregistreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistreActionPerformed
        // TODO add your handling code here:
        Archive.ecriture("c:/temp/listeFraisRepresentants.txt", registreFrais);
        JOptionPane.showMessageDialog(null, "Vos données ont été enregistrées", "Merci", JOptionPane.INFORMATION_MESSAGE);
        reset();
    }//GEN-LAST:event_btnEnregistreActionPerformed

    private void rbtnTrans2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTrans2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnTrans2ActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenSaisie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenSaisie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenSaisie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenSaisie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenSaisie().setVisible(true);
            }
        });


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjou;
    private javax.swing.JButton btnEnregistre;
    private javax.swing.ButtonGroup btnG;
    private javax.swing.JButton btnQui;
    private javax.swing.JButton btnSup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblLimite;
    private javax.swing.JLabel lblMont;
    private javax.swing.JLabel lblRep;
    private javax.swing.JLabel lblType;
    private javax.swing.JRadioButton rbtnHeb;
    private javax.swing.JRadioButton rbtnHeber2;
    private javax.swing.JRadioButton rbtnRepas;
    private javax.swing.JRadioButton rbtnRepas2;
    private javax.swing.JRadioButton rbtnTra;
    private javax.swing.JRadioButton rbtnTrans2;
    private javax.swing.JTable tblAffichage;
    private javax.swing.JComboBox<String> trans;
    private javax.swing.JFormattedTextField txtDate;
    private javax.swing.JTextField txtMont;
    private javax.swing.JTextField txtRep;
    // End of variables declaration//GEN-END:variables
}
